### ISSUE TITLE
OPAM installation seems to silently fail on older versions of Ubuntu

### ISSUE THREAD

**Issue by MagnusS** [xapi-project/ocaml-xen-lowlevel-libs#82]
`opam install xenctrl` succeeds, but `ocamlfind query xenlight` fails.

See also https://github.com/mirage/jitsu/issues/29

**Comment by djs55** [comment]
Hm. I think it's about time a failure to compile `xenlight` is a hard
failure. I'll take a look.

On Fri, Oct 16, 2015 at 4:55 PM, Magnus Skjegstad <notifications@github.com>
wrote:

> opam install xenctrl succeeds, but ocamlfind query xenlight fails.
>
> See also mirage/jitsu#29 <https://github.com/mirage/jitsu/issues/29>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/xapi-project/ocaml-xen-lowlevel-libs/issues/82>.
>



-- 
Dave Scott

**Comment by gaborigloi** [comment]
fe6453b2 fixed this by making `xenlight` mandatory. Installation works and `xenlight` is installed on all supported Ubuntu versions (16.10, 16.04, 14.04), except 12.04, but that will become [unsupported this month](https://en.wikipedia.org/wiki/Ubuntu_version_history#Table_of_versions).
